### PR TITLE
IntelliJ 2021.1

### PR DESCRIPTION
**Pull request by tomasz-zablocki**
This PR aligns the plugin with latest (2021.1) IDEA release

### CODE REVIEW

**Comment by ui-mariusz-zawadzki** [comment]
@guillaumem-theodo : Hi. Please take a look at this PR, would be nice to have this plugin in most recent Intellij version.

**Review by guillaumem-theodo — APPROVED** [review]

**Comment by guillaumem-theodo** [comment]
Thanks Mariusz for your help. 
I will submit the updated plugin to Jetbrains today

**Comment by guillaumem-theodo** [comment]
Plugin updated in Jetbrains plugin repository. Waiting for Jetbrains approval

**Comment by ui-mariusz-zawadzki** [comment]
@guillaumem-theodo: Thanks for quick response merge.

 KUDOS to @tomasz-zablocki , who created the PR. I just found while checking if this is already in progress.

**Pull request merged**
